### ISSUE TITLE
Just to have it in one place, the target of this rule is:

### ISSUE THREAD

**Issue by MattyPe** [coreruleset/plugin-registry#5] opened 2021-12-22 14:50 UTC
Just to have it in one place, the target of this rule is:
```
# 920120: PL1 : FILES_NAMES, FILES
#                ['\";=] but allowed:
#                &[aAoOuUyY]uml); &[aAeEiIoOuU]circ; &[eEiIoOuUyY]acute;
#                &[aAeEiIoOuU]grave; &[cC]cedil; &[aAnNoO]tilde; &amp; &apos;
```

_Originally posted by @fzipi in https://github.com/coreruleset/coreruleset/issues/2333#issuecomment-991618051_

**Comment by theseion** [comment] 2022-04-30 06:19
@fzipi Any clue what this issue is about?

**Comment by fzipi** [comment] 2022-05-28 12:41
No.

@MattyPe Can you give us more information about what you reported here? If not we are closing this as not a bug 🤷

**Closed as completed** 2023-06-07 12:48 UTC
Labels: invalid
